{% set name = "xattr" %}
{% set version = "0.9.9" %}
{% set bundle = "tar.gz" %}
{% set hash = "09cb7e1efb3aa1b4991d6be4eb25b73dc518b4fe894f0915f5b0dcede972f346" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  skip: true  # [win]
  entry_points:
    - xattr = xattr.tool:main

  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - cffi >=1.0.0

  run:
    - python
    - cffi >=1.0.0

test:
  imports:
    - xattr

  commands:
    - xattr --help

about:
  home: https://github.com/xattr/xattr
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Python wrapper for extended filesystem attributes
  dev_url: https://github.com/xattr/xattr

extra:
  recipe-maintainers:
    - pmlandwehr
